<?php

namespace Serhii\Bundle\TestBundle\Repository;

/**
 * CompanyCrudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyCrudRepository extends \Doctrine\ORM\EntityRepository
{
}
